const PAYMENT_URL="YOUR PAYMENT FUNCTION URL ";

const ORDER_DATA = {
  "custID":"USER_12365478955",
  "custEmail":"abc@gmail.com",
  "custPhone":"4567893210"
};
const STATUS_LOADING="PAYMENT_LOADING";
const STATUS_SUCCESSFUL="PAYMENT_SUCCESSFUL";

const STATUS_PENDING="PAYMENT_PENDING";

const STATUS_FAILED="PAYMENT_FAILED";
const STATUS_CHECKSUM_FAILED="PAYMENT_CHECKSUM_FAILED";

